CREATE SCHEMA IF NOT EXISTS commerce;

CREATE TABLE commerce.account (
  user_id SERIAL PRIMARY KEY, 
  email VARCHAR (255) UNIQUE NOT NULL, 
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE commerce.product (
  product_id SERIAL PRIMARY KEY, 
  product_name VARCHAR (255) UNIQUE NOT NULL, 
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
